import type { Lesson, Shortcut } from "./types";

export const groupLabels = {
  research: "Học tập & nghiên cứu",
  admin: "Hành chính & tổ chức",
  advanced: "Word nâng cao",
} as const;

const academicExamples = {
  report: "Tên đề tài: Tác động của AI đến phương pháp học tập của sinh viên. Trường: Đại học ABC. Khoa: Công nghệ thông tin. Học phần: Quản lý dự án giáo dục.",
  survey: "Câu 1: Bạn thường dùng Word cho mục đích nào? A. Làm tiểu luận B. Làm báo cáo C. Làm biểu mẫu D. Khác. Câu 2: Bạn gặp lỗi Word nào nhiều nhất?",
  citation: "Nguyễn Văn A (2024). Ứng dụng công nghệ trong giáo dục. NXB Giáo dục. https://example.edu.vn",
};

export const lessons: Lesson[] = [
  {
    id: "page-setup-document-properties",
    group: "research",
    title: "Thiết lập tài liệu: khổ giấy, lề, font, page border",
    subtitle: "Bước nền để tài liệu đại học không bị lệch bố cục khi in hoặc nộp PDF.",
    minutes: 20,
    difficulty: "Nền tảng",
    outcome: "Thiết lập được file Word A4, đúng hướng giấy, lề, font, cỡ chữ, giãn dòng và viền trang khi cần.",
    checkpoints: ["A4 đúng", "Lề rõ thông số", "Font thống nhất", "Biết xem Print Preview"],
    steps: [
      "Mở file Word mới hoặc file bài tập thô.",
      "Vào Layout để chỉnh Size, Orientation và Margins.",
      "Chọn Size là A4. Dùng Portrait cho văn bản thường, Landscape khi có bảng ngang rộng.",
      "Chọn Margins > Custom Margins và nhập Top, Bottom, Left, Right theo yêu cầu.",
      "Vào Home để chọn font chữ, cỡ chữ, giãn dòng và căn lề đoạn văn.",
      "Nếu cần khung viền trang, vào Design hoặc Layout > Page Borders.",
      "Chọn viền mảnh, nghiêm túc cho tiểu luận hoặc báo cáo học thuật.",
      "Mở File > Print để kiểm tra trước khi in hoặc xuất PDF.",
    ],
    tips: [
      "Với tài liệu dài, hãy đặt định dạng từ đầu trước khi nhập nội dung để tránh lệch bố cục hàng loạt.",
      "Không nên chỉnh lề bằng cách kéo thước nếu đề yêu cầu số đo cụ thể.",
      "Landscape chỉ nên dùng cho phần có bảng ngang rộng; nếu chỉ một phần cần ngang, hãy tách section.",
    ],
    mistakes: [
      "Viết xong mới chỉnh toàn bộ khiến bảng, ảnh và mục lục dễ vỡ.",
      "Dùng Enter nhiều lần để đẩy nội dung sang trang khác thay vì dùng Page Break hoặc Section Break.",
    ],
    quickCommands: [
      { label: "Lề thường dùng", value: "Top 2cm; Bottom 2cm; Left 3cm; Right 2cm", note: "Thông số hay gặp trong báo cáo, tiểu luận." },
      { label: "Khổ giấy chuẩn", value: "Layout > Size > A4", note: "Kiểm tra trước khi định dạng sâu." },
      { label: "Xem trước khi in", value: "File > Print > Print Preview", note: "Phát hiện nhanh lỗi lệch lề hoặc tràn trang." },
    ],
    miniQuiz: [
      { question: "Khi nào nên dùng Landscape?", answer: "Khi tài liệu có bảng hoặc biểu đồ ngang rộng cần thêm chiều ngang." },
      { question: "Vì sao nên đặt định dạng từ đầu?", answer: "Vì chỉnh sau dễ làm lệch bố cục, đặc biệt với ảnh, bảng, mục lục và số trang." },
      { question: "Page Border nên dùng kiểu gì cho báo cáo học thuật?", answer: "Nét mảnh, gọn, không nhiều màu hoặc hiệu ứng." },
      { question: "Muốn kiểm tra văn bản in ra có lệch không, vào đâu?", answer: "File > Print để xem Print Preview." },
    ],
    examples: [
      {
        title: "Ví dụ: tạo file tiểu luận chuẩn A4",
        brief: "Dùng nội dung mẫu rồi thiết lập trang trước khi nhập phần thân bài.",
        sample: academicExamples.report,
        expected: ["Khổ giấy A4", "Hướng Portrait", "Lề trái 3cm", "Font thống nhất", "Print Preview không tràn lề"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: sửa file thô thành file sẵn sàng nhập bài",
        prompt: "Tạo một file Word mới, nhập 5 dòng thông tin đề tài và định dạng lại toàn bộ trang.",
        tasks: ["Đặt A4, Portrait", "Đặt lề Top/Bottom 2cm, Left 3cm, Right 2cm", "Font Times New Roman 13", "Giãn dòng 1.5", "Thêm page border mảnh"],
        selfCheck: ["Không dùng Space để căn lề", "Print Preview hiển thị cân đối", "Không có dòng bị tràn ra ngoài vùng in"],
      },
    ],
  },
  {
    id: "normal-style-paragraph",
    group: "research",
    title: "Normal Style và Paragraph chuẩn học thuật",
    subtitle: "Định nghĩa thân văn bản một lần để toàn bộ bài viết tự đồng bộ.",
    minutes: 18,
    difficulty: "Nền tảng",
    outcome: "Sửa được Normal Style với font, cỡ chữ, căn đều, thụt dòng đầu và khoảng cách đoạn đúng.",
    checkpoints: ["Modify Style", "Justified", "First line", "Spacing 6pt", "Line spacing 1.5"],
    steps: [
      "Vào Home, nhìn sang nhóm Styles.",
      "Nhấp phải vào Normal và chọn Modify.",
      "Trong Formatting, chọn Times New Roman, cỡ 13 hoặc 14 tùy quy định khoa.",
      "Bấm Format ở góc trái dưới, chọn Paragraph.",
      "Đặt Alignment là Justified để căn đều hai bên.",
      "Ở Indentation > Special, chọn First line và đặt 1cm đến 1.27cm.",
      "Đặt Spacing Before 6pt, After 6pt và Line spacing 1.5 lines.",
      "Nhấn OK hai lần. Từ giờ đoạn văn thường sẽ theo định dạng này.",
    ],
    tips: [
      "Normal Style là nền của thân bài; sửa Normal tốt hơn quét chọn toàn bộ rồi sửa thủ công.",
      "Nếu copy từ Internet, hãy Paste Special > Keep Text Only rồi để Style của tài liệu áp định dạng.",
    ],
    mistakes: [
      "Thụt đầu dòng bằng Space hoặc Tab từng dòng khiến bố cục không đều.",
      "Chỉ chỉnh một đoạn mẫu nhưng quên cập nhật Style nên đoạn sau vẫn sai.",
    ],
    quickCommands: [
      { label: "Paragraph học thuật", value: "Justified; First line 1cm; Before 6pt; After 6pt; Line spacing 1.5", note: "Cấu hình thân bài theo PDF." },
      { label: "Dán sạch định dạng", value: "Paste Special > Keep Text Only", note: "Hữu ích khi copy từ Internet." },
    ],
    miniQuiz: [
      { question: "Normal Style dùng cho phần nào?", answer: "Thân văn bản thông thường của tài liệu." },
      { question: "First line trong Paragraph để làm gì?", answer: "Tự động thụt lề dòng đầu tiên của mỗi đoạn." },
      { question: "Vì sao nên căn Justified trong báo cáo?", answer: "Để hai mép đoạn văn thẳng, nhìn chính thức và dễ đọc." },
      { question: "Before/After 6pt giúp gì?", answer: "Tạo khoảng cách đoạn thoáng hơn mà không cần nhấn Enter thêm." },
    ],
    examples: [
      {
        title: "Ví dụ: đoạn thân bài chưa chuẩn",
        brief: "Đoạn văn copy từ nhiều nguồn bị lẫn font và khoảng cách.",
        sample: "Quản lý dự án giáo dục cần kế hoạch rõ ràng.  Nhóm sinh viên phải phân công nhiệm vụ, theo dõi tiến độ và tổng hợp minh chứng trước khi nộp báo cáo.",
        expected: ["Font Times New Roman 13 hoặc 14", "Căn đều hai bên", "Dòng đầu thụt 1cm", "Không có Enter dư giữa các đoạn"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: chuẩn hóa 3 đoạn văn",
        prompt: "Nhập 3 đoạn văn bất kỳ về chủ đề học đại học, sau đó chỉnh Normal Style để toàn bộ đoạn tự cập nhật.",
        tasks: ["Modify Normal", "Đặt Paragraph theo thông số học thuật", "Dán thêm 1 đoạn từ nguồn khác bằng Keep Text Only", "Kiểm tra tất cả đoạn có cùng style"],
        selfCheck: ["Không có đoạn khác font", "Không dùng nhiều Space để thụt dòng", "Khoảng cách đoạn đến từ Paragraph, không phải Enter dư"],
      },
    ],
    lab: {
      title: "",
      brief: "Mô phỏng phần Normal Style bằng thao tác trực tiếp trên văn bản: sửa nội dung, nhấn mạnh ý chính và tạo đoạn văn sạch.",
      initialContent:
        "<p>Quan ly du an giao duc can ke hoach ro rang. Nhom sinh vien phai phan cong nhiem vu, theo doi tien do va tong hop minh chung truoc khi nop bao cao.</p><p>Hay bo sung mot doan ket luan ngan ve vai tro cua dinh dang van ban.</p>",
      instructions: [
        "Giữ nội dung thành ít nhất hai đoạn văn riêng.",
        "Bôi đậm cụm 'ke hoach ro rang' hoặc một ý chính tương đương.",
        "Thêm cụm 'dinh dang van ban' vào phần kết luận.",
      ],
      checks: [
        { id: "paragraph-content", label: "Có nội dung về định dạng văn bản", type: "contains", value: "dinh dang van ban" },
        { id: "bold-focus", label: "Có một ý chính được in đậm", type: "bold" },
        { id: "has-text", label: "Giữ nội dung quản lý dự án giáo dục", type: "contains", value: "du an giao duc" },
      ],
    },
  },
  {
    id: "heading-toc-navigation",
    group: "research",
    title: "Heading, Navigation Pane và mục lục tự động",
    subtitle: "Tổ chức tiểu luận, báo cáo, nhật ký thực tập và khóa luận bằng cấu trúc thật.",
    minutes: 26,
    difficulty: "Cần luyện",
    outcome: "Tạo được Heading 1/2/3, mục lục tự động và cập nhật mục lục đúng sau khi sửa bài.",
    checkpoints: ["Heading đúng cấp", "TOC tự động", "Update Field", "Navigation Pane"],
    steps: [
      "Chọn tiêu đề chương hoặc mục lớn, áp dụng Heading 1.",
      "Chọn mục con như 1.1, 1.2 và áp dụng Heading 2.",
      "Chọn mục nhỏ hơn như 1.1.1 và áp dụng Heading 3.",
      "Muốn chỉnh kiểu Heading, nhấp phải Heading > Modify, đặt font, cỡ, đậm/nghiêng và spacing.",
      "Đặt con trỏ tại nơi muốn chèn mục lục, thường sau trang bìa hoặc lời cảm ơn.",
      "Vào References > Table of Contents và chọn mẫu tự động.",
      "Sau khi sửa nội dung, nhấp phải vào mục lục > Update Field.",
      "Chọn Update entire table khi thay tên, thêm, xóa hoặc đổi cấp tiêu đề.",
    ],
    tips: [
      "Tô đậm tiêu đề không tạo cấu trúc. Muốn mục lục chạy đúng, bắt buộc dùng Heading.",
      "Navigation Pane giúp soi nhanh bố cục toàn bài và phát hiện tiêu đề sai cấp.",
    ],
    mistakes: [
      "Gõ mục lục thủ công bằng dấu chấm nên số trang sai khi chỉnh bài.",
      "Chỉ chọn Update page numbers trong khi đã đổi tên hoặc thêm tiêu đề mới.",
    ],
    quickCommands: [
      { label: "Mở Navigation Pane", value: "Ctrl + F > Headings", note: "Xem toàn bộ cấu trúc bên trái." },
      { label: "Cập nhật mục lục", value: "Right click TOC > Update Field > Update entire table", note: "Dùng sau khi chỉnh cấu trúc bài." },
      { label: "Cập nhật field", value: "F9", note: "Cập nhật field đang chọn." },
    ],
    miniQuiz: [
      { question: "Heading 1 thường dùng cho gì?", answer: "Tiêu đề lớn, chương hoặc phần chính." },
      { question: "Heading 2 thường dùng cho gì?", answer: "Mục con của Heading 1 như 1.1, 1.2." },
      { question: "Khi đổi tên tiêu đề, chọn update mục lục kiểu nào?", answer: "Update entire table." },
      { question: "Tô đậm tiêu đề có đủ để mục lục nhận không?", answer: "Không. Phải áp dụng Heading." },
      { question: "Navigation Pane giúp gì?", answer: "Kiểm tra nhanh cấu trúc tiêu đề và nhảy tới từng mục." },
    ],
    examples: [
      {
        title: "Ví dụ: cấu trúc báo cáo nhóm",
        brief: "Chuyển dàn ý thành Heading để sinh mục lục tự động.",
        sample: "1. Mở đầu\n1.1 Lý do chọn đề tài\n1.2 Mục tiêu nghiên cứu\n2. Nội dung\n2.1 Kế hoạch thực hiện\n2.2 Kết quả khảo sát\n3. Kết luận",
        expected: ["Mở đầu/Nội dung/Kết luận là Heading 1", "Các mục 1.1, 1.2 là Heading 2", "Mục lục hiển thị đúng cấp"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: tạo mục lục cho báo cáo 3 chương",
        prompt: "Nhập dàn ý mẫu vào Word và tạo mục lục tự động.",
        tasks: ["Áp dụng Heading 1 cho 3 chương", "Áp dụng Heading 2 cho ít nhất 6 mục con", "Chèn Table of Contents", "Đổi tên một mục rồi Update entire table"],
        selfCheck: ["Mục lục không gõ tay", "Số trang trong mục lục cập nhật", "Navigation Pane hiển thị đúng thứ bậc"],
      },
    ],
    lab: {
      title: "",
      brief: "Tập biến dàn ý thô thành cấu trúc tài liệu có Heading để chuẩn bị cho mục lục tự động.",
      initialContent:
        "<p>Bao cao nhom du an giao duc</p><p>Mo dau</p><p>Ly do chon de tai</p><p>Muc tieu nghien cuu</p><p>Noi dung</p><p>Ke hoach thuc hien</p><p>Ket luan</p>",
      instructions: [
        "Chuyển tiêu đề chính thành Heading 1.",
        "Chuyển ít nhất hai mục con thành Heading 2.",
        "Giữ cụm 'Bao cao nhom du an giao duc' trong tài liệu.",
      ],
      checks: [
        { id: "main-heading", label: "Có Heading 1", type: "heading", value: "h2" },
        { id: "sub-heading", label: "Có Heading 2", type: "heading", value: "h3" },
        { id: "report-title", label: "Giữ tên báo cáo", type: "contains", value: "Bao cao nhom du an giao duc" },
      ],
    },
  },
  {
    id: "page-number-section-break",
    group: "research",
    title: "Đánh số trang và Section Break",
    subtitle: "Tách bìa, mục lục và nội dung chính để kiểm soát số trang đúng yêu cầu.",
    minutes: 28,
    difficulty: "Cần luyện",
    outcome: "Biết dùng Page Number, Different First Page, Section Break và Link to Previous để xử lý số trang.",
    checkpoints: ["Page Number", "Different First Page", "Section Break", "Link to Previous"],
    steps: [
      "Vào Insert > Page Number và chọn vị trí số trang: đầu trang, cuối trang hoặc current position.",
      "Nếu trang bìa không hiện số, mở Header/Footer và tick Different First Page.",
      "Với báo cáo dài, đặt con trỏ cuối trang bìa hoặc mục lục.",
      "Vào Layout > Breaks > Section Breaks > Next Page để tách phần.",
      "Mở Header/Footer ở section mới và bỏ Link to Previous nếu muốn chỉnh riêng.",
      "Vào Page Number > Format Page Numbers để chọn kiểu số và Start at.",
      "Bật Show/Hide để nhìn Page Break, Section Break và xóa break dư nếu cần.",
    ],
    tips: [
      "Muốn mục lục không hiện số trang nhưng nội dung chính có số, phải dùng Section Break.",
      "Không nhấn Enter thật nhiều để đẩy sang trang mới. Hãy dùng Ctrl + Enter hoặc Section Break.",
    ],
    mistakes: [
      "Dùng Page Break thay cho Section Break nên không chỉnh được header/footer riêng.",
      "Quên bỏ Link to Previous làm số trang các phần nối sai.",
    ],
    quickCommands: [
      { label: "Ngắt trang nhanh", value: "Ctrl + Enter", note: "Sang trang mới không tạo nhiều Enter dư." },
      { label: "Hiện ký tự ẩn", value: "Ctrl + Shift + 8", note: "Nhìn break, tab, dấu đoạn." },
      { label: "Tạo section mới", value: "Layout > Breaks > Next Page", note: "Cần cho số trang/header/footer riêng." },
    ],
    miniQuiz: [
      { question: "Section Break khác Page Break thế nào?", answer: "Section Break tạo phần có thiết lập riêng; Page Break chỉ sang trang mới." },
      { question: "Muốn trang bìa không có số, có thể dùng tùy chọn nào?", answer: "Different First Page." },
      { question: "Nút nào cần tắt khi header/footer nối sai?", answer: "Link to Previous." },
      { question: "Muốn bắt đầu số trang từ 1 ở phần nội dung, vào đâu?", answer: "Insert > Page Number > Format Page Numbers > Start at: 1." },
    ],
    examples: [
      {
        title: "Ví dụ: báo cáo có bìa, mục lục, nội dung",
        brief: "Bìa không số, mục lục có thể dùng i, ii, nội dung bắt đầu từ 1.",
        sample: "Trang 1: Bìa\nTrang 2: Mục lục\nTrang 3: Mở đầu\nTrang 4: Nội dung chính",
        expected: ["Bìa không số", "Nội dung chính bắt đầu trang 1", "Header/Footer không kéo nhầm giữa section"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: chia section cho báo cáo",
        prompt: "Tạo file 4 trang gồm bìa, mục lục, chương 1 và chương 2.",
        tasks: ["Chèn Section Break sau bìa", "Chèn Section Break sau mục lục", "Tắt Link to Previous ở nội dung chính", "Đặt nội dung chính Start at 1"],
        selfCheck: ["Không dùng Enter dư để tạo trang", "Bật ¶ thấy đúng section", "Số trang không xuất hiện trên bìa"],
      },
    ],
  },
  {
    id: "objects-captions-citations",
    group: "research",
    title: "Hình, bảng, caption, cross-reference và trích dẫn",
    subtitle: "Làm tài liệu nghiên cứu có hình/bảng chuyên nghiệp và nguồn tham khảo rõ ràng.",
    minutes: 34,
    difficulty: "Nâng cao",
    outcome: "Chèn được hình, bảng, biểu đồ, caption, danh mục hình/bảng, cross-reference và citation.",
    checkpoints: ["Insert Caption", "Cross-reference", "Citation", "Bibliography", "Table of Figures"],
    steps: [
      "Đặt con trỏ vào vị trí cần chèn đối tượng.",
      "Vào Insert > Pictures, Table hoặc Chart để chèn hình, bảng hoặc biểu đồ.",
      "Sau khi chèn, chỉnh kích thước và Wrap Text phù hợp.",
      "Chọn đối tượng, vào References > Insert Caption để thêm chú thích.",
      "Dùng Cross-reference khi cần nhắc lại hình hoặc bảng trong nội dung.",
      "Vào References > Insert Citation > Add New Source để nhập nguồn tài liệu.",
      "Chọn Bibliography hoặc References để lập danh mục tài liệu tham khảo.",
      "Muốn tạo danh mục hình/bảng, dùng References > Insert Table of Figures.",
    ],
    tips: [
      "Caption tự động giúp số hình/bảng cập nhật khi bạn thêm hoặc xóa đối tượng.",
      "Nhập nguồn từ đầu sẽ giảm rủi ro thiếu tài liệu tham khảo ở cuối bài.",
      "Cross-reference chuyên nghiệp hơn gõ 'xem hình 2' bằng tay.",
    ],
    mistakes: [
      "Gõ caption thủ công nên số hình không tự đổi.",
      "Kéo ảnh tự do mà không chỉnh Wrap Text khiến chữ chạy lung tung.",
      "Đợi cuối bài mới nhập nguồn nên dễ sót citation.",
    ],
    quickCommands: [
      { label: "Chèn caption", value: "References > Insert Caption", note: "Dùng cho hình, bảng, biểu đồ." },
      { label: "Chèn nguồn", value: "References > Insert Citation > Add New Source", note: "Lưu thông tin tác giả, năm, NXB, link." },
      { label: "Danh mục hình/bảng", value: "References > Insert Table of Figures", note: "Chọn Caption label là Figure hoặc Table." },
    ],
    miniQuiz: [
      { question: "Insert Caption dùng để làm gì?", answer: "Tạo chú thích và đánh số tự động cho hình/bảng." },
      { question: "Cross-reference giúp gì?", answer: "Liên kết tới hình/bảng/heading và cập nhật khi số thứ tự đổi." },
      { question: "Bibliography nằm ở tab nào?", answer: "References." },
      { question: "Nếu thêm hình mới, danh mục hình cần làm gì?", answer: "Update Field hoặc Update Table." },
    ],
    examples: [
      {
        title: "Ví dụ: hình khảo sát trong báo cáo",
        brief: "Chèn biểu đồ khảo sát và dẫn lại trong đoạn phân tích.",
        sample: "Theo Hình 1, tỷ lệ sinh viên dùng Word để làm báo cáo nhóm chiếm đa số. " + academicExamples.citation,
        expected: ["Hình có caption", "Đoạn văn dùng cross-reference", "Nguồn được thêm vào Bibliography"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: tạo danh mục hình",
        prompt: "Chèn 2 hình bất kỳ và 1 bảng vào file Word, sau đó tạo danh mục hình/bảng.",
        tasks: ["Chèn caption cho từng hình", "Chèn caption cho bảng", "Dẫn lại ít nhất 1 hình bằng Cross-reference", "Tạo Table of Figures"],
        selfCheck: ["Không gõ số hình bằng tay", "Khi thêm hình mới, số caption cập nhật", "Danh mục hình đúng thứ tự"],
      },
    ],
  },
  {
    id: "academic-forms-appendix-export",
    group: "research",
    title: "Trang bìa, phụ lục, phiếu khảo sát và xuất PDF",
    subtitle: "Những phần phụ nhưng rất hay xuất hiện trong bài nộp đại học.",
    minutes: 36,
    difficulty: "Cần luyện",
    outcome: "Tạo được trang bìa, phần nhận xét, phụ lục, bảng câu hỏi, checkbox, tab leader, text box và xuất PDF ít lỗi font.",
    checkpoints: ["Cover page", "Appendix", "Survey table", "Checkbox", "Tab leader", "Export PDF"],
    steps: [
      "Tạo trang bìa riêng ở đầu file, thêm tên trường, khoa, đề tài, lớp, họ tên và năm học.",
      "Chèn logo hoặc khung bằng Insert > Pictures, Text Box hoặc Shapes nếu cần.",
      "Tạo khu vực nhận xét/xác nhận ở cuối tài liệu bằng Table hoặc Text Box, chừa khoảng ký tên.",
      "Đặt phụ lục ở cuối văn bản, dùng Heading cho Phụ lục 1, Phụ lục 2.",
      "Tạo bảng câu hỏi bằng Insert > Table, chia cột câu hỏi, lựa chọn, ghi chú, trả lời.",
      "Dùng Bullets, Numbering hoặc Developer > Check Box Content Control cho danh sách chọn.",
      "Dùng Tabs... để tạo điểm dừng Tab và Leader nếu cần dòng chấm điền thông tin.",
      "Trước khi nộp, dùng File > Save As hoặc Export > PDF và mở lại PDF để kiểm tra font/bố cục.",
    ],
    tips: [
      "Trang bìa đẹp nên gọn, ít màu, cân đối và đúng mẫu đơn vị.",
      "Tab Stops & Leader tốt hơn gõ nhiều dấu chấm bằng tay.",
      "Xuất PDF dạng Standard để giữ chất lượng tốt hơn Minimum size khi nộp báo cáo.",
    ],
    mistakes: [
      "Tạo dòng điền thông tin bằng cách gõ dấu chấm thủ công.",
      "Phụ lục để lộn xộn, không dùng Heading nên người đọc khó tra.",
      "Xuất PDF nhưng không mở lại kiểm tra, dẫn tới lỗi font hoặc vỡ layout.",
    ],
    quickCommands: [
      { label: "Checkbox rỗng", value: "2610 + Alt + X", note: "Tạo ký tự ô vuông rỗng." },
      { label: "Checkbox tick", value: "2611 + Alt + X", note: "Tạo ô vuông có dấu tick." },
      { label: "Tab leader", value: "Home > Paragraph launcher > Tabs... > Leader", note: "Tạo dòng chấm chuyên nghiệp." },
      { label: "Xuất PDF", value: "File > Export hoặc Save As > PDF", note: "Mở PDF lại để kiểm tra." },
    ],
    miniQuiz: [
      { question: "Phiếu khảo sát đẹp cần ưu tiên gì?", answer: "Nhìn vào là biết ngay chỗ nào cần trả lời." },
      { question: "Phụ lục nên đặt ở đâu?", answer: "Cuối văn bản và đặt tên rõ bằng Heading." },
      { question: "Tab leader thay thế thói quen nào?", answer: "Gõ dấu chấm thủ công để tạo dòng điền thông tin." },
      { question: "Vì sao nên xuất PDF trước khi nộp?", answer: "Để giữ font và bố cục ổn định khi mở trên máy khác." },
      { question: "Text Box + Shapes phù hợp với phần nào?", answer: "Trang bìa, khung thông tin hoặc sơ đồ đơn giản." },
    ],
    examples: [
      {
        title: "Ví dụ: phiếu khảo sát sinh viên",
        brief: "Dùng bảng và checkbox để tạo phiếu dễ trả lời.",
        sample: academicExamples.survey,
        expected: ["Bảng có cột câu hỏi/lựa chọn/ghi chú", "Có checkbox", "Khoảng cách dễ đọc", "Không lệch khi in"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: tạo phụ lục khảo sát",
        prompt: "Thiết kế một phụ lục gồm bảng câu hỏi 5 dòng và phần xác nhận cuối trang.",
        tasks: ["Tạo Heading 'Phụ lục 1: Phiếu khảo sát'", "Tạo bảng 4 cột", "Chèn checkbox cho lựa chọn", "Tạo dòng ký tên bằng Tab leader", "Xuất PDF và mở kiểm tra"],
        selfCheck: ["Bảng không tràn trang", "Checkbox đều hàng", "PDF không lỗi font", "Phần ký tên không sát mép giấy"],
      },
    ],
    lab: {
      title: "",
      brief: "Tập dựng một phụ lục khảo sát bằng bảng, danh sách và nội dung dễ đọc.",
      initialContent:
        "<p>Phu luc 1: Phieu khao sat sinh vien</p><p>Hay tao bang gom cac cot: Cau hoi, Lua chon, Ghi chu.</p><p>Noi dung can co it nhat hai cau hoi ve viec hoc Word.</p>",
      instructions: [
        "Tạo một bảng để chứa câu hỏi khảo sát.",
        "Thêm danh sách bullet hoặc numbered list cho các lựa chọn.",
        "Giữ cụm 'Phieu khao sat sinh vien' trong tài liệu.",
      ],
      checks: [
        { id: "survey-table", label: "Có bảng khảo sát", type: "table" },
        { id: "survey-list", label: "Có danh sách lựa chọn", type: "list" },
        { id: "survey-title", label: "Giữ tiêu đề phiếu khảo sát", type: "contains", value: "Phieu khao sat sinh vien" },
      ],
    },
  },
  {
    id: "administrative-documents",
    group: "admin",
    title: "Văn bản hành chính: quốc hiệu, chữ ký, logo và căn chỉnh",
    subtitle: "Tạo kế hoạch, công văn, tờ trình, biên bản họp hoặc thư mời gọn và nghiêm túc.",
    minutes: 30,
    difficulty: "Cần luyện",
    outcome: "Dựng được đầu văn bản hành chính, phần chữ ký/duyệt, logo và bố cục căn chỉnh ổn định.",
    checkpoints: ["Quốc hiệu", "Tiêu ngữ", "Chữ ký", "Logo", "Inspect Document"],
    steps: [
      "Căn giữa phần đầu trang bằng Ctrl + E.",
      "Dòng Quốc hiệu gõ in hoa, in đậm, cỡ 12-13.",
      "Dòng Tiêu ngữ gõ in thường, in đậm, cỡ 13-14 và có gạch nối giữa các cụm từ.",
      "Chèn đường kẻ liền nét dưới Tiêu ngữ bằng Shape Line, dài vừa dòng chữ.",
      "Cuối văn bản, chèn khu vực ký tên, chức danh, phần duyệt hoặc xác nhận.",
      "Nếu dùng chữ ký tay, Insert > Pictures, sau đó Picture Format > Remove Background hoặc Color > Set Transparent Color.",
      "Căn chỉnh chữ ký bằng bảng không viền hoặc tab để không bị lệch.",
      "Chèn logo bằng Insert > Pictures; dùng Wrap Text để logo không đẩy vỡ dòng.",
      "Trước khi gửi file, vào File > Info > Check for Issues > Inspect Document để xóa metadata khi cần.",
    ],
    tips: [
      "Văn bản hành chính nên ít hiệu ứng, font rõ, bố cục cân xứng.",
      "Bảng không viền là cách an toàn để căn khối ký tên và phần duyệt.",
      "Inspect Document giúp xóa thông tin cá nhân ẩn mà mắt thường không thấy.",
    ],
    mistakes: [
      "Căn bằng nhiều Space khiến mở trên máy khác bị lệch.",
      "Logo quá to làm văn bản mất tính nghiêm túc.",
      "Chỉ xóa chữ nhìn thấy nhưng quên metadata trong file.",
    ],
    quickCommands: [
      { label: "Căn giữa", value: "Ctrl + E", note: "Dùng cho Quốc hiệu - Tiêu ngữ." },
      { label: "Xóa nền chữ ký", value: "Picture Format > Remove Background", note: "Làm chữ ký sạch hơn." },
      { label: "Kiểm tra thông tin ẩn", value: "File > Info > Check for Issues > Inspect Document", note: "Xóa metadata trước khi gửi." },
    ],
    miniQuiz: [
      { question: "Quốc hiệu nên định dạng thế nào?", answer: "In hoa, in đậm, cỡ 12-13 và căn giữa." },
      { question: "Tiêu ngữ nên định dạng thế nào?", answer: "In thường, in đậm, cỡ 13-14, có gạch nối giữa các cụm từ." },
      { question: "Công cụ nào giúp xóa nền chữ ký tay?", answer: "Remove Background hoặc Set Transparent Color." },
      { question: "Muốn xóa metadata file Word, dùng gì?", answer: "Inspect Document trong File > Info > Check for Issues." },
      { question: "Vì sao không nên căn bằng Space?", answer: "Vì dễ lệch khi đổi font, cỡ chữ hoặc mở ở máy khác." },
    ],
    examples: [
      {
        title: "Ví dụ: thư mời họp nhóm dự án",
        brief: "Tạo mẫu thư mời có quốc hiệu, tiêu ngữ, nội dung và khối ký tên.",
        sample: "THƯ MỜI\nKính gửi: Thành viên Nhóm 2\nNội dung: Họp thống nhất kế hoạch dự án giáo dục.\nThời gian: 19h30, thứ Sáu.\nĐịa điểm: Phòng học B203.",
        expected: ["Đầu văn bản đúng bố cục", "Nội dung căn đều", "Khối ký tên bên phải", "Không dùng Space để căn"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: dựng công văn ngắn",
        prompt: "Tạo một văn bản hành chính 1 trang về việc mời họp triển khai dự án học tập.",
        tasks: ["Tạo Quốc hiệu - Tiêu ngữ", "Chèn đường kẻ dưới Tiêu ngữ", "Viết phần Kính gửi và nội dung", "Tạo khối ký tên", "Chạy Inspect Document"],
        selfCheck: ["Đầu trang cân giữa", "Chữ ký không lệch", "Không có metadata cá nhân nếu cần gửi ra ngoài", "Logo nhỏ và đúng vị trí nếu có"],
      },
    ],
  },
  {
    id: "tips-shortcuts",
    group: "advanced",
    title: "Mẹo hay và phím tắt thao tác nhanh",
    subtitle: "Những thao tác tiết kiệm thời gian khi làm bài Word trong lớp và khi thi MOS.",
    minutes: 24,
    difficulty: "Nền tảng",
    outcome: "Ghi nhớ và áp dụng được các phím tắt cơ bản, định dạng, di chuyển, chọn nhanh và thủ thuật nâng cao.",
    checkpoints: ["F4", "Shift F3", "Ctrl Enter", "AutoCorrect", "Smart Lookup"],
    steps: [
      "Dùng F4 để lặp lại thao tác gần nhất như tô màu, định dạng, chèn dòng.",
      "Dùng Shift + F3 để đổi chữ hoa, chữ thường hoặc viết hoa chữ cái đầu.",
      "Dùng Ctrl + Enter để chèn trang trắng nhanh.",
      "Nháy đúp để chọn một từ, click 3 lần để chọn cả đoạn.",
      "Gõ --- rồi Enter để tạo đường kẻ ngang; gõ === để tạo đường kẻ đôi.",
      "Gõ 2610/2611/2612 rồi Alt + X để tạo checkbox rỗng/tick/x.",
      "Dùng Alt + Shift + mũi tên lên/xuống để di chuyển đoạn văn.",
      "Thiết lập AutoCorrect để viết tắt thành cụm dài, ví dụ qhtn thành Cộng hòa xã hội chủ nghĩa Việt Nam.",
    ],
    tips: [
      "Học phím tắt theo tình huống, không học một danh sách dài vô cảm.",
      "F4 cực hữu ích khi cần áp dụng cùng định dạng cho nhiều đoạn rời nhau.",
    ],
    mistakes: [
      "Nhớ phím tắt nhưng không biết dùng vào việc gì nên nhanh quên.",
      "Dùng thủ thuật đường kẻ tự động nhưng không biết cách undo hoặc xóa khi tạo nhầm.",
    ],
    quickCommands: [
      { label: "Lặp thao tác", value: "F4", note: "Làm lại thao tác gần nhất." },
      { label: "Chuyển hoa/thường", value: "Shift + F3", note: "Đổi case vùng chọn." },
      { label: "Đường kẻ mảnh", value: "--- + Enter", note: "Tạo horizontal line nhanh." },
      { label: "AutoCorrect", value: "File > Options > Proofing > AutoCorrect Options", note: "Tạo cụm viết tắt." },
    ],
    miniQuiz: [
      { question: "F4 dùng để làm gì?", answer: "Lặp lại thao tác gần nhất." },
      { question: "Shift + F3 dùng để làm gì?", answer: "Chuyển chữ hoa, chữ thường hoặc viết hoa chữ cái đầu." },
      { question: "Ctrl + Enter dùng để làm gì?", answer: "Chèn ngắt trang nhanh." },
      { question: "Gõ 2611 + Alt + X tạo gì?", answer: "Ô checkbox có dấu tick." },
      { question: "AutoCorrect giúp gì?", answer: "Tự động thay cụm viết tắt bằng nội dung dài đã thiết lập." },
    ],
    examples: [
      {
        title: "Ví dụ: tạo cụm viết tắt hành chính",
        brief: "Tự động thay qhtn thành cụm dài.",
        sample: "qhtn -> Cộng hòa xã hội chủ nghĩa Việt Nam",
        expected: ["Mở AutoCorrect Options", "Thêm cặp replace/with", "Gõ thử trong tài liệu"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: hoàn thành 6 thao tác trong 3 phút",
        prompt: "Mở Word và thao tác liên tục với một đoạn văn bản mẫu.",
        tasks: ["Dùng Shift + F3 đổi chữ", "Dùng F4 lặp định dạng", "Chèn trang bằng Ctrl + Enter", "Tạo 3 loại đường kẻ", "Tạo 3 checkbox bằng Alt + X", "Di chuyển đoạn bằng Alt + Shift + mũi tên"],
        selfCheck: ["Không dùng chuột quá nhiều", "Hiểu từng phím tắt dùng cho tình huống nào", "Có thể lặp lại thao tác không nhìn hướng dẫn"],
      },
    ],
  },
  {
    id: "common-errors",
    group: "advanced",
    title: "Soát lỗi và kiểm tra bố cục Word",
    subtitle: "Bài tổng kết cuối lộ trình: đọc tài liệu như bản in, tìm lỗi bố cục, field, section, hình bảng và mục lục trước khi nộp.",
    minutes: 24,
    difficulty: "Cần luyện",
    outcome: "Biết quy trình soát lại file Word theo đúng tinh thần PDF: không chỉ sửa chính tả, mà kiểm tra cả cách hiển thị trên trang in.",
    checkpoints: ["Review", "Navigation Pane", "Print Preview", "Update Field", "Section Break"],
    steps: [
      "Bắt đầu bằng tab Review > Spelling & Grammar để xử lý lỗi chính tả và ngữ pháp cơ bản.",
      "Mở Navigation Pane để xem cấu trúc Heading; nếu mục lục thiếu mục, thường là do tiêu đề chưa được áp dụng Heading đúng cấp.",
      "Kiểm tra lại số trang, mục lục, danh mục hình, danh mục bảng, caption và cross-reference vì đây đều là field có thể cần Update Field.",
      "Chuyển sang File > Print hoặc Print Preview để nhìn tài liệu như bản nộp thật; nhiều lỗi lệch lề, tràn trang, bảng vượt lề chỉ lộ ra ở bước này.",
      "Bật ký tự ẩn bằng Home > ¶ nếu thấy trang trống, khoảng trống lạ, số trang sai hoặc nội dung bị đẩy sang trang khác.",
      "Kiểm tra Section Break trước khi sửa header, footer, số trang bìa, mục lục và nội dung chính; không nên xóa break theo cảm tính.",
      "Với hình và bảng, kiểm tra Wrap Text, kích thước, caption và thứ tự đánh số; nếu thêm hoặc xóa đối tượng thì cập nhật lại field.",
      "Với bảng khảo sát, phụ lục hoặc biểu mẫu, đọc lại độ rộng cột, căn lề ô, dòng bị tách trang và khả năng người đọc biết chỗ nào cần trả lời.",
    ],
    tips: [
      "PDF nhấn mạnh rằng nhiều lỗi không nằm ở chữ, mà nằm ở bố cục; vì vậy phải xem cả nội dung lẫn cách hiển thị trên trang in.",
      "Tài liệu dài nên nhập nguồn, dùng Heading, caption và section từ đầu; làm thủ công về cuối sẽ rất dễ sót và tốn thời gian sửa lại.",
      "Trang bìa, phụ lục, phần nhận xét và bảng câu hỏi cần gọn, có khoảng trống hợp lý, không làm rối mắt người đọc.",
    ],
    mistakes: [
      "Chỉ sửa chính tả mà bỏ qua Print Preview.",
      "Gõ mục lục, danh mục hình, danh mục bảng bằng tay thay vì dùng Heading, Caption và Update Field.",
      "Dùng Enter hoặc Space để đẩy nội dung, căn bảng, tách bìa hoặc tạo khoảng trống.",
      "Xóa Section Break mà không hiểu nó đang điều khiển header, footer hay số trang nào.",
    ],
    quickCommands: [],
    miniQuiz: [],
    examples: [],
    exercises: [],
  },
  {
    id: "mail-merge",
    group: "advanced",
    title: "Mail Merge từ danh sách dữ liệu",
    subtitle: "Tạo thư mời, nhãn, giấy chứng nhận hoặc email hàng loạt mà vẫn cá nhân hóa.",
    minutes: 35,
    difficulty: "Nâng cao",
    outcome: "Kết nối được danh sách người nhận, chèn merge field, preview và finish merge.",
    checkpoints: ["Mailings", "Select Recipients", "Insert Merge Field", "Preview Results", "Finish & Merge"],
    steps: [
      "Mở Mailings > Start Mail Merge và chọn kiểu tài liệu như Letters, E-mail Messages, Envelopes hoặc Labels.",
      "Nhập phần nội dung chính giống nhau cho mọi người nhận.",
      "Chọn Select Recipients để kết nối danh sách dữ liệu.",
      "Có thể tạo danh sách mới trong Word hoặc dùng file Excel có sẵn.",
      "Chèn trường trộn bằng Insert Merge Field, Address Block hoặc Greeting Line.",
      "Chọn Preview Results để xem từng bản trộn và kiểm tra dữ liệu.",
      "Chọn Finish & Merge để in, xuất tài liệu hoặc gửi email.",
    ],
    tips: [
      "Excel nguồn nên có hàng đầu là tên cột, không gộp ô, không dòng trống đầu bảng.",
      "Preview vài bản ghi dài nhất để kiểm tra tràn dòng trước khi Finish & Merge.",
    ],
    mistakes: [
      "Tên cột Excel mơ hồ hoặc có dòng trống làm Word nhận sai field.",
      "Quên Preview Results nên xuất hàng loạt mới phát hiện lỗi.",
    ],
    quickCommands: [
      { label: "Bắt đầu trộn thư", value: "Mailings > Start Mail Merge > Letters", note: "Chọn kiểu tài liệu." },
      { label: "Chọn nguồn", value: "Mailings > Select Recipients", note: "Kết nối Excel hoặc tạo list mới." },
      { label: "Xem thử", value: "Mailings > Preview Results", note: "Kiểm tra trước khi xuất." },
    ],
    miniQuiz: [
      { question: "Mail Merge nằm ở tab nào?", answer: "Mailings." },
      { question: "Insert Merge Field dùng để làm gì?", answer: "Chèn trường dữ liệu từ danh sách vào mẫu văn bản." },
      { question: "Bước nào giúp kiểm tra từng người nhận trước khi xuất?", answer: "Preview Results." },
      { question: "Finish & Merge dùng khi nào?", answer: "Khi đã kiểm tra xong và muốn in, xuất hoặc gửi hàng loạt." },
    ],
    examples: [
      {
        title: "Ví dụ: thư mời họp cá nhân hóa",
        brief: "Mỗi người nhận có tên, lớp và thời gian riêng.",
        sample: "Kính gửi <<HoTen>>, mời bạn tham dự buổi họp nhóm dự án giáo dục lúc <<ThoiGian>> tại <<DiaDiem>>.",
        expected: ["HoTen/ThoiGian/DiaDiem là merge field", "Preview từng bản ghi", "Không còn dấu << >> sau khi merge"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: tạo 5 thư mời",
        prompt: "Tạo bảng dữ liệu 5 người nhận trong Excel hoặc Word rồi trộn thành thư mời.",
        tasks: ["Tạo cột HoTen, Lop, ThoiGian, DiaDiem", "Kết nối danh sách", "Chèn ít nhất 3 merge field", "Preview đủ 5 bản ghi", "Finish & Merge ra tài liệu mới"],
        selfCheck: ["Tên từng người hiện đúng", "Không có field bị trống", "Dòng dài không tràn bố cục"],
      },
    ],
  },
  {
    id: "review-protect-compare",
    group: "advanced",
    title: "Track Changes, Comments, Protect Document và Compare",
    subtitle: "Làm việc nhóm, duyệt sửa, khóa tài liệu và so sánh phiên bản Word.",
    minutes: 34,
    difficulty: "Nâng cao",
    outcome: "Theo dõi chỉnh sửa, góp ý, khóa file hoặc vùng chỉnh sửa và so sánh hai phiên bản tài liệu.",
    checkpoints: ["Track Changes", "Comments", "Restrict Editing", "Encrypt Password", "Compare"],
    steps: [
      "Mở Review > Track Changes để bật theo dõi thay đổi.",
      "Chọn chế độ hiển thị All Markup, Simple Markup hoặc No Markup tùy mục đích xem.",
      "Dùng Accept hoặc Reject để duyệt từng thay đổi; dùng Next/Previous để di chuyển.",
      "Bôi đen đoạn cần góp ý, chọn Review > New Comment hoặc Ctrl + Alt + M.",
      "Reply, Resolve hoặc Delete comment khi phần trao đổi đã hoàn tất.",
      "Muốn khóa bằng mật khẩu, vào File > Info > Protect Document > Encrypt with Password.",
      "Muốn giới hạn chỉnh sửa, vào Review > Restrict Editing và chọn kiểu giới hạn.",
      "Muốn so sánh hai file, vào Review > Compare > Compare, chọn Original và Revised document.",
    ],
    tips: [
      "Track Changes phù hợp khi cần minh bạch ai sửa gì trong bài nhóm.",
      "Comments nên dùng cho trao đổi, không nên sửa âm thầm vào nội dung người khác.",
      "Trước khi nộp bản cuối, kiểm tra còn markup/comment nào không.",
    ],
    mistakes: [
      "Quên tắt Track Changes trước khi nộp bản cuối.",
      "Accept All khi chưa đọc kỹ làm mất dấu sửa quan trọng.",
      "Quên mật khẩu Protect Document khiến khó mở lại file.",
    ],
    quickCommands: [
      { label: "Bật Track Changes", value: "Review > Track Changes", note: "Theo dõi chỉnh sửa." },
      { label: "Comment nhanh", value: "Ctrl + Alt + M", note: "Thêm nhận xét." },
      { label: "Khóa chỉnh sửa", value: "Review > Restrict Editing", note: "Giới hạn vùng được sửa." },
      { label: "So sánh file", value: "Review > Compare > Compare", note: "Đối chiếu bản gốc và bản sửa." },
    ],
    miniQuiz: [
      { question: "Track Changes dùng để làm gì?", answer: "Theo dõi các thay đổi trong tài liệu." },
      { question: "Comments khác Track Changes ở đâu?", answer: "Comments là góp ý/trao đổi; Track Changes là ghi lại chỉnh sửa thật." },
      { question: "Muốn khóa tài liệu bằng mật khẩu vào đâu?", answer: "File > Info > Protect Document > Encrypt with Password." },
      { question: "Restrict Editing dùng để làm gì?", answer: "Giới hạn kiểu hoặc vùng nội dung được phép chỉnh sửa." },
      { question: "Compare Documents cần chọn hai file nào?", answer: "Original document và Revised document." },
    ],
    examples: [
      {
        title: "Ví dụ: duyệt báo cáo nhóm",
        brief: "Một bạn sửa nội dung, một bạn phản biện bằng comment.",
        sample: "Đoạn gốc: Mục tiêu dự án là xây dựng website học MOS. Đoạn sửa: Mục tiêu dự án là xây dựng website tự học MOS Word cho sinh viên.",
        expected: ["Track Changes hiển thị phần sửa", "Comment giải thích lý do sửa", "Có thể Accept hoặc Reject"],
      },
    ],
    exercises: [
      {
        title: "Exercise test: kiểm soát phiên bản",
        prompt: "Tạo hai bản tài liệu ngắn, sửa bản thứ hai rồi dùng Compare để xem khác biệt.",
        tasks: ["Bật Track Changes và sửa 3 câu", "Thêm 2 comments", "Accept 1 thay đổi, Reject 1 thay đổi", "Khóa tài liệu read-only thử nghiệm", "Compare bản gốc và bản sửa"],
        selfCheck: ["Biết chuyển All Markup/Simple Markup", "Bản cuối không còn comment thừa", "Compare hiển thị đúng khác biệt"],
      },
    ],
  },
];

export const shortcuts: Shortcut[] = [
  { keys: "Ctrl + N", action: "Tạo tài liệu mới", category: "Tài liệu" },
  { keys: "Ctrl + O", action: "Mở tài liệu", category: "Tài liệu" },
  { keys: "Ctrl + S", action: "Lưu tài liệu", category: "Tài liệu" },
  { keys: "Ctrl + C / X / V", action: "Sao chép, cắt, dán", category: "Tài liệu" },
  { keys: "Ctrl + Z / Y", action: "Hoàn tác hoặc làm lại thao tác", category: "Tài liệu" },
  { keys: "Ctrl + A", action: "Chọn toàn bộ văn bản", category: "Tài liệu" },
  { keys: "Ctrl + F", action: "Tìm kiếm và mở Navigation Pane", category: "Di chuyển" },
  { keys: "Ctrl + H", action: "Tìm kiếm và thay thế", category: "Tài liệu" },
  { keys: "Ctrl + B / I / U", action: "In đậm, in nghiêng, gạch chân", category: "Định dạng" },
  { keys: "Ctrl + Shift + > / <", action: "Tăng hoặc giảm kích thước chữ", category: "Định dạng" },
  { keys: "Ctrl + L / R / E / J", action: "Căn trái, phải, giữa, đều hai bên", category: "Định dạng" },
  { keys: "Ctrl + 1 / 2 / 5", action: "Giãn dòng 1.0, 2.0 hoặc 1.5", category: "Định dạng" },
  { keys: "Ctrl + ← / →", action: "Di chuyển qua một từ", category: "Di chuyển" },
  { keys: "Ctrl + Home / End", action: "Về đầu hoặc cuối tài liệu", category: "Di chuyển" },
  { keys: "Shift + Mũi tên", action: "Bôi đen văn bản theo hướng", category: "Di chuyển" },
  { keys: "Click 3 lần", action: "Chọn toàn bộ đoạn văn", category: "Di chuyển" },
  { keys: "Ctrl + Enter", action: "Chèn ngắt trang nhanh", category: "Tài liệu" },
  { keys: "Ctrl + Shift + 8", action: "Hiện hoặc ẩn ký tự định dạng", category: "Tài liệu" },
  { keys: "F4", action: "Lặp lại thao tác gần nhất", category: "Nâng cao" },
  { keys: "Shift + F3", action: "Chuyển chữ hoa, chữ thường, viết hoa đầu câu", category: "Nâng cao" },
  { keys: "Alt + Shift + ↑ / ↓", action: "Di chuyển đoạn văn lên hoặc xuống", category: "Nâng cao" },
  { keys: "Ctrl + Alt + M", action: "Thêm comment", category: "Nâng cao" },
  { keys: "F9", action: "Cập nhật field đã chọn", category: "Nâng cao" },
  { keys: "Ctrl + A > F9", action: "Cập nhật toàn bộ field trong tài liệu", category: "Nâng cao" },
  { keys: "2610 + Alt + X", action: "Tạo checkbox rỗng", category: "Nâng cao" },
  { keys: "2611 + Alt + X", action: "Tạo checkbox có tick", category: "Nâng cao" },
  { keys: "--- + Enter", action: "Tạo đường kẻ ngang mảnh", category: "Nâng cao" },
];
