import type { ExamBlueprint, ExamAttempt, Question, User } from "./types.js";

export const users: User[] = [
  {
    id: "u-admin",
    role: "admin",
    name: "Admin MOS Center",
    email: "admin@mos.edu.vn",
    lastLoginAt: new Date().toISOString(),
  },
  {
    id: "u-student-1",
    role: "student",
    name: "Tran Minh Anh",
    email: "anh@student.edu.vn",
    lastLoginAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "u-student-2",
    role: "student",
    name: "Le Quoc Bao",
    email: "bao@student.edu.vn",
    lastLoginAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];

export const questions: Question[] = [
  {
    id: "q-layout-1",
    domain: "manage-documents",
    skillTags: ["layout", "page-setup", "print-preview"],
    type: "project-task",
    difficulty: "foundation",
    title: "Thiết lập tài liệu A4",
    prompt: "Đặt khổ giấy A4, Portrait, lề trái 3cm và kiểm tra Print Preview.",
    expectedAnswer: ["A4", "Portrait", "Left 3cm", "Print Preview"],
    estimatedSeconds: 180,
    points: 10,
  },
  {
    id: "q-format-1",
    domain: "insert-format-text",
    skillTags: ["paragraph", "normal-style", "line-spacing"],
    type: "sequence",
    difficulty: "medium",
    title: "Chuẩn hóa Normal Style",
    prompt: "Sắp xếp các bước chỉnh Normal Style cho thân bài học thuật.",
    expectedAnswer: ["Home > Styles", "Right click Normal", "Modify", "Format > Paragraph", "OK"],
    estimatedSeconds: 150,
    points: 10,
  },
  {
    id: "q-table-1",
    domain: "manage-tables-lists",
    skillTags: ["table", "form-layout"],
    type: "sequence",
    difficulty: "medium",
    title: "Tạo biểu mẫu bằng Table",
    prompt: "Sắp xếp thao tác tạo biểu mẫu khảo sát bằng bảng.",
    expectedAnswer: ["Insert > Table", "Nhập dữ liệu", "Distribute Rows", "Borders", "Save"],
    estimatedSeconds: 210,
    points: 10,
  },
  {
    id: "q-reference-1",
    domain: "create-manage-references",
    skillTags: ["heading", "toc", "field-update"],
    type: "project-task",
    difficulty: "advanced",
    title: "Tạo mục lục tự động",
    prompt: "Áp dụng Heading 1/2, chèn Table of Contents và cập nhật toàn bộ mục lục.",
    expectedAnswer: ["Heading 1", "Heading 2", "Table of Contents", "Update entire table"],
    estimatedSeconds: 240,
    points: 15,
  },
  {
    id: "q-graphic-1",
    domain: "insert-format-graphic-elements",
    skillTags: ["caption", "cross-reference", "wrap-text"],
    type: "project-task",
    difficulty: "medium",
    title: "Caption và tham chiếu hình",
    prompt: "Chèn caption cho hình và tạo cross-reference trong đoạn văn.",
    expectedAnswer: ["Insert Caption", "Figure label", "Cross-reference"],
    estimatedSeconds: 220,
    points: 10,
  },
  {
    id: "q-review-1",
    domain: "manage-collaboration",
    skillTags: ["track-changes", "comments", "protect-document"],
    type: "multiple-choice",
    difficulty: "foundation",
    title: "Hiểu Track Changes",
    prompt: "Ẩn markup có đồng nghĩa với việc đã xóa thay đổi không?",
    expectedAnswer: "Không. Phải Accept hoặc Reject thay đổi.",
    estimatedSeconds: 45,
    points: 5,
  },
  {
    id: "q-mailmerge-1",
    domain: "manage-documents",
    skillTags: ["mail-merge", "data-source", "preview-results"],
    type: "project-task",
    difficulty: "advanced",
    title: "Mail Merge thư mời",
    prompt: "Kết nối danh sách Excel, chèn merge fields và Preview Results trước khi Finish.",
    expectedAnswer: ["Select Recipients", "Insert Merge Field", "Preview Results", "Finish & Merge"],
    estimatedSeconds: 300,
    points: 15,
  },
];

export const blueprints: ExamBlueprint[] = [
  {
    id: "mos-word-mock-1",
    name: "MOS Word Mock Test 1",
    totalQuestions: 5,
    durationMinutes: 50,
    mosScaleMin: 100,
    mosScaleMax: 1000,
    domainMatrix: [
      { domain: "manage-documents", percent: 30, difficulties: ["foundation", "medium", "advanced"] },
      { domain: "insert-format-text", percent: 20, difficulties: ["foundation", "medium"] },
      { domain: "manage-tables-lists", percent: 20, difficulties: ["medium"] },
      { domain: "create-manage-references", percent: 20, difficulties: ["medium", "advanced"] },
      { domain: "manage-collaboration", percent: 10, difficulties: ["foundation"] },
    ],
  },
];

export const attempts: ExamAttempt[] = [
  {
    id: "attempt-seed-1",
    studentId: "u-student-1",
    blueprintId: "mos-word-mock-1",
    questionIds: ["q-layout-1", "q-format-1", "q-table-1", "q-reference-1", "q-review-1"],
    startedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    submittedAt: new Date(Date.now() - 3 * 86400000 + 42 * 60000).toISOString(),
    rawScore: 35,
    mosScore: 700,
    answers: [
      { questionId: "q-layout-1", answer: ["A4", "Portrait", "Left 3cm", "Print Preview"], elapsedSeconds: 170, isCorrect: true },
      { questionId: "q-format-1", answer: ["Home > Styles", "Right click Normal", "Modify", "Format > Paragraph", "OK"], elapsedSeconds: 160, isCorrect: true },
      { questionId: "q-table-1", answer: ["Insert > Table", "Borders", "Nhập dữ liệu", "Distribute Rows", "Save"], elapsedSeconds: 280, isCorrect: false },
      { questionId: "q-reference-1", answer: ["Heading 1", "Heading 2", "Table of Contents", "Update entire table"], elapsedSeconds: 260, isCorrect: true },
      { questionId: "q-review-1", answer: "Không. Phải Accept hoặc Reject thay đổi.", elapsedSeconds: 55, isCorrect: true },
    ],
  },
  {
    id: "attempt-seed-2",
    studentId: "u-student-2",
    blueprintId: "mos-word-mock-1",
    questionIds: ["q-layout-1", "q-format-1", "q-table-1", "q-mailmerge-1", "q-review-1"],
    startedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    submittedAt: new Date(Date.now() - 10 * 86400000 + 48 * 60000).toISOString(),
    rawScore: 20,
    mosScore: 460,
    answers: [
      { questionId: "q-layout-1", answer: ["A4", "Portrait", "Left 3cm", "Print Preview"], elapsedSeconds: 210, isCorrect: true },
      { questionId: "q-format-1", answer: ["Modify", "Home > Styles", "Right click Normal", "Format > Paragraph", "OK"], elapsedSeconds: 220, isCorrect: false },
      { questionId: "q-table-1", answer: ["Insert > Table", "Nhập dữ liệu", "Distribute Rows", "Borders", "Save"], elapsedSeconds: 260, isCorrect: true },
      { questionId: "q-mailmerge-1", answer: ["Insert Merge Field", "Select Recipients", "Finish & Merge"], elapsedSeconds: 390, isCorrect: false },
      { questionId: "q-review-1", answer: "Có", elapsedSeconds: 70, isCorrect: false },
    ],
  },
];
